health_check_port: 8095
server_config:
  processor_config:
    type: "account_transactions_processor"
    channel_size: 100
  transaction_stream_config:
    indexer_grpc_data_service_address: "grpc://127.0.0.1:50053"
    request_name_header: "account_transactions_processor"
    auth_token: ""
  processor_mode:
    type: "default" 
    initial_starting_version: 0
  db_config:
    type: postgres_config
    connection_string: postgresql://postgres:password@127.0.0.1:5432/indexer