health_check_port: 8098
server_config:
  processor_config:
    type: "token_v2_processor"
    channel_size: 100
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.cedra.dev:443"
    auth_token: ""
    request_name_header: "token_v2_processor"
  processor_mode:
    type: "default" 
    initial_starting_version: 0
  db_config:
    type: "postgres_config"
    connection_string: "postgresql://postgres:password@localhost:5432/indexer"
